### ISSUE TITLE
Drag and drop failing in Firefox

### ISSUE THREAD

**Issue by nicbou** [nicbou/markdown-notes#54]
https://sentry.io/markdown-notes/markdown-notes/issues/193712264/

```
TypeError: e.dataTransfer.types.indexOf is not a function
  at isImageDrag (/static/CACHE/js/7b4c79cea920.js:1581:369)
  at onDragOver (/static/CACHE/js/7b4c79cea920.js:1581:520)
  at Sf (angular.js:3497:2)
  at func (angular.js:3485:8)
```

This is because Chrome returns an Array for dataTransfer.types while Firefox returns a DOMStringList.

This is fixed in Firefox 52, so I'm just keeping this ticket around for reference

https://www.fxsitecompat.com/en-CA/docs/2016/datatransfer-types-is-now-domstringlist-instead-of-array/

**Comment by nicbou** [comment]
Firefox 52 is slated for release in March 2017.

https://developer.mozilla.org/en-US/Firefox/Releases/52
